"""
Compiles collected findings into a Markdown report and a raw JSON dump.
"""
import json
import os
from datetime import datetime, timezone


def save_json(findings: dict, out_dir: str, basename: str) -> str:
    path = os.path.join(out_dir, f"{basename}.json")
    with open(path, "w") as f:
        json.dump(findings, f, indent=2, default=str)
    return path


def save_markdown(findings: dict, out_dir: str, basename: str) -> str:
    path = os.path.join(out_dir, f"{basename}.md")
    lines = []
    lines.append(f"# OSINT Report: {findings.get('target', 'unknown')}")
    lines.append(f"\n_Generated: {datetime.now(timezone.utc).isoformat()}Z_\n")

    if "domain" in findings:
        d = findings["domain"]
        lines.append("## Domain Recon\n")
        lines.append(f"**Domain:** `{d['domain']}`\n")

        lines.append("### WHOIS")
        for k, v in d.get("whois", {}).items():
            lines.append(f"- **{k}:** {v}")
        lines.append("")

        lines.append("### DNS Records")
        for rtype, vals in d.get("dns", {}).items():
            if vals:
                lines.append(f"- **{rtype}:** {', '.join(map(str, vals)) if isinstance(vals, list) else vals}")
        lines.append("")

        subs = d.get("subdomains", [])
        lines.append(f"### Subdomains ({d.get('subdomain_count', 0)} found via crt.sh)")
        for s in subs[:100]:
            lines.append(f"- {s}")
        if len(subs) > 100:
            lines.append(f"- ...and {len(subs) - 100} more (see JSON)")
        lines.append("")

    if "username" in findings:
        u = findings["username"]
        lines.append("## Username Footprint\n")
        lines.append(f"**Username:** `{u['username']}`\n")
        lines.append(f"### Found on {len(u['found'])} platform(s)")
        for r in u["found"]:
            lines.append(f"- **{r['platform']}**: {r['url']}")
        if u.get("errors"):
            lines.append(f"\n_{len(u['errors'])} platform(s) errored out during check._")
        lines.append("")

    if "breach" in findings:
        b = findings["breach"]
        lines.append("## Breach Exposure Check\n")
        if b.get("error"):
            lines.append(f"_{b['error']}_\n")
        else:
            lines.append(f"**Email:** `{b.get('email')}`  ")
            lines.append(f"**Breaches found:** {b.get('breach_count', 0)}\n")
            for br in b.get("breaches", []):
                lines.append(f"- **{br['name']}** ({br['date']}) — exposed: {', '.join(br['data_classes'] or [])}")
        lines.append("")

    if "search" in findings:
        s = findings["search"]
        lines.append("## Web Search\n")
        lines.append(f"**Query:** {s.get('query')}  ")
        lines.append(f"**Backend:** {s.get('backend')}\n")
        if s.get("error"):
            lines.append(f"_Error: {s['error']}_\n")
        else:
            for r in s.get("results", []):
                lines.append(f"- **[{r['title']}]({r['url']})**  \n  {r['snippet']}")
        lines.append("")

    if "entity" in findings:
        e = findings["entity"]
        lines.append("## Entity / Name Search\n")
        lines.append(f"**Target:** {e.get('target')}  ")
        lines.append(f"**Backend:** {e.get('backend')}\n")
        if e.get("note"):
            lines.append(f"> {e['note']}\n")
        for label, outcome in e.get("queries", {}).items():
            lines.append(f"### {label}")
            lines.append(f"`{outcome.get('query')}`\n")
            if outcome.get("error"):
                lines.append(f"_Error: {outcome['error']}_\n")
                continue
            if not outcome.get("results"):
                lines.append("_No results._\n")
                continue
            for r in outcome.get("results", []):
                lines.append(f"- **[{r['title']}]({r['url']})**  \n  {r['snippet']}")
            lines.append("")

    if "metadata" in findings:
        m = findings["metadata"]
        lines.append("## Document/Image Metadata\n")
        lines.append(f"**Source:** {m.get('source')}  ")
        lines.append(f"**Type:** {m.get('filetype')}\n")
        meta = m.get("metadata", {})
        if isinstance(meta, dict):
            for k, v in meta.items():
                lines.append(f"- **{k}:** {v}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by osint_agent. Verify all findings independently before publication. "
                  "Passive/public sources only — no active scanning was performed._")

    content = "\n".join(lines)
    with open(path, "w") as f:
        f.write(content)
    return path
